# Generated by Django 6.0.5 on 2026-05-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_distance',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('reserved', 'reserved'), ('active', 'active'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
