# Generated by Django 6.0.5 on 2026-05-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_core', '0002_booking_estimated_distance_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_license_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_reference_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_selfie_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='driver_license_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='driver_selfie_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
